const CinemaRoomAction = {

    GET_LIST_CINEMAROOM: "GET_LIST_CINEMAROOM",
    GETTING_LIST_CINEMAROOM: "GETTING_LIST_CINEMAROOM",
    GET_LIST_CINEMAROOM_SUCCESS: "GGET_LIST_CINEMAROOM_SUCCESS",
    GET_LIST_CINEMAROOM_FAILURE: "GET_LIST_CINEMAROOM_FAILURE",
    
    CREATE_CINEMAROOM: "CREATE_CINEMAROOM",

    DELETE_CINEMAROOM: "DELETE_CINEMAROOM",
};

export default CinemaRoomAction;
