const CustomerAction = {
    GET_CUSTOMER_DETAIL: 'GET_CUSTOMER_DETAIL',
    GETING_USER_DETAIL: 'GETING_USER_DETAIL',
    GET_CUSTOMER_DETAIL_SUCCESS: 'GET_CUSTOMER_DETAIL_SUCCESS',
    GET_CUSTOMER_DETAIL_FAILUSE: 'GET_CUSTOMER_DETAIL_FAILURE',

    CHANGE_PROFILE: 'CHANGE_PROFILE',
    CHANGING_PROFILE: 'CHANGING_PROFILE',
    CHANGE_PROFILE_SUCCESS: 'CHANGE_PROFILE_SUCCESS',
    CHANGE_PROFILE_FAILUSE: 'CHANGE_PROFILE_FAILUSE',

    GET_ALL_CUSTOMER: 'GET_ALL_CUSTOMER',
    GETTING_ALL_CUSTOMER: 'GETTING_ALL_CUSTOMER',
    GET_ALL_CUSTOMER_SUCCESS: 'GET_ALL_CUSTOMER_SUCCESS',
    GET_ALL_CUSTOMER_FAILUSE: 'GET_ALL_CUSTOMER_FAILUSE',

    DELETE_CUSTOMER: 'DELETE_CUSTOMER',

    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER'
};

export default CustomerAction;
