const FilmAction = {
    GET_ALL_FILM: 'GET_ALL_FILM',
    GETTING_ALL_FILM: 'GETTING_ALL_FILM',
    GET_ALL_FILM_SUCCESS: 'GET_ALL_FILM_SUCCESS',
    GET_ALL_FILM_FAILSE: 'GET_ALL_FILM_FAILSE',

    GET_DETAIL_FILM: 'GET_DETAIL_FILM',
    GETTING_DETAIL_FILM: 'GETTING_DETAIL_FILM',
    GET_DETAIL_FILM_SUCCESS: 'GET_DETAIL_FILM_SUCCESS',
    GET_DETAIL_FILM_FAILSE: 'GET_DETAIL_FILM_FAILSE',

    GET_DETAIL_SHOWTIME: 'GET_DETAIL_SHOWTIME',
    GETTING_DETAIL_SHOWTIME: 'GETTING_DETAIL_SHOWTIME',
    GET_DETAIL_SHOWTIME_SUCCESS: 'GET_DETAIL_SHOWTIME_SUCCESS',
    GET_DETAIL_SHOWTIME_FAILSE: 'GET_DETAIL_SHOWTIME_FAILSE',

    CREATE_FILM: 'CREATE_FILM',
    CREATING_FILM: 'CREATING_FILM',
    CREATE_FILM_SUCCESS: 'CREATE_FILM_SUCCESS',
    CREATE_FILM_FAILSE: 'CREATE_FILM_FAILSE',

    DETAIL_FILM: 'DETAIL_FILM',
    DETAILING_FILM: 'CREATING_FILM',
    DETAIL_FILM_SUCCESS: 'DETAIL_FILM_SUCCESS',
    DETAIL_FILM_FAILSE: 'DETAIL_FILM_FAILSE',

    UPDATE_FILM: 'UPDATE_FILM',
    UPDATING_FILM: 'UPDATING_FILM',
    UPDATE_FILM_SUCCESS: 'UPDATE_FILM_SUCCESS',
    UPDATE_FILM_FAILSE: 'UPDATE_FILM_FAILSE',

    GET_SHOWTIME_BY_BRANCH: 'GET_SHOWTIME_BY_BRANCH',
    GETTING_SHOWTIME_BY_BRANCH: 'GETTING_SHOWTIME_BY_BRANCH',
    GET_SHOWTIME_BY_BRANCH_SUCCESS: 'GET_SHOWTIME_BY_BRANCH_SUCCESS',
    GET_SHOWTIME_BY_BRANCH_FAILSE: 'GET_SHOWTIME_BY_BRANCH_FAILSE',

    GET_TYPE_FILM: 'GET_TYPE_FILM',
};

export default FilmAction;