const ShowtimeAction = {

    GET_ALL_SHOW_TIME: "GET_ALL_SHOW_TIME",
    GETTING_ALL_SHOW_TIME: "GETTING_ALL_SHOW_TIME",
    GET_ALL_SHOW_TIME_SUCCESS: "GET_ALL_SHOW_TIME_SUCCESS",
    GET_ALL_SHOW_TIME_FAILURE: "GET_ALL_SHOW_TIME_FAILURE",

    CREATE_SHOW_TIME: "CREATE_SHOW_TIME",
    CREATING_SHOW_TIME: "CREATING_SHOW_TIME",
    CREATE_SHOW_TIME_SUCCESS: "CREATE_SHOW_TIME_SUCCESS",
    CREATE_SHOW_TIME_FAILURE: "CREATE_SHOW_TIME_FAILURE",
};

export default ShowtimeAction;
