const CustomerAction = {
    GET_CUSTOMER_DETAIL: 'GET_CUSTOMER_DETAIL',
    GETING_USER_DETAIL: 'GETING_USER_DETAIL',
    GET_CUSTOMER_DETAIL_SUCCESS: 'GET_CUSTOMER_DETAIL_SUCCESS',
    GET_CUSTOMER_DETAIL_FAILUSE: 'GET_CUSTOMER_DETAIL_FAILURE',
};

export default CustomerAction;
