const LoginAction = {
    SUBMIT_LOGIN: 'SUBMIT_LOGIN',
    SUBMITING_LOGIN: 'SUBMITING_LOGIN',
    SUBMIT_LOGIN_SUCCESS: 'SUBMIT_LOGIN_SUCCESS',
    SUBMIT_LOGIN_FAILURE: 'SUBMIT_LOGIN_FAILURE',

    SUBMIT_REGISTER: 'SUBMIT_REGISTER',
    SUBMITING_REGISTER: 'SUBMITING_REGISTER',
    SUBMIT_REGISTER_SUCCESS: 'SUBMITING_REGISTER_SUCCESS',
    SUBMIT_REGISTER_FAILURE: 'SUBMITING_REGISTER_FAILURE',

    GET_USER_DETAIL: 'GET_USER_DETAIL',
    GETING_USER_DETAIL: 'GETING_USER_DETAIL',
    GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
    GET_USER_DETAIL_FAILUSE: 'GET_USER_DETAIL_FAILURE',

    CHANGE_PROFILE: 'CHANGE_PROFILE',
    CHANGING_PROFILE: 'CHANGING_PROFILE',
    CHANGE_PROFILE_SUCCESS: 'CHANGE_PROFILE_SUCCESS',
    CHANGE_PROFILE_FAILUSE: 'CHANGE_PROFILE_FAILUSE',

    GET_ALL_EMPLOYEE: 'GET_ALL_EMPLOYEE',
    GETTING_ALL_EMPLOYEE: 'GETTING_ALL_EMPLOYEE',
    GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
    GET_ALL_EMPLOYEE_FAILUSE: 'GET_ALL_EMPLOYEE_FAILUSE',

    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    CREATING_EMPLOYEE: 'CREATING_EMPLOYEE',
    CREATE_EMPLOYEE_SUCCESS: 'CREATE_EMPLOYEE_SUCCESS',
    CREATE_EMPLOYEE_FAILUSE: 'CREATE_EMPLOYEE_FAILUSE',

    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',

    ISADMIN: 'ISADMIN',
};

export default LoginAction;
