const ReportAction = {
    GET_REPORT_BY_BRANCH: 'GET_REPORT_BY_BRANCH',
    GETTING_REPORT_BY_BRANCH: 'GETTING_REPORT_BY_BRANCH',
    GET_REPORT_BY_BRANCH_SUCCESS: 'GET_REPORT_BY_BRANCH_SUCCESS',
    GET_REPORT_BY_BRANCH_FAILSE: 'GET_REPORT_BY_BRANCH_FAILSE',

    GET_REPORT_BY_DATE: 'GET_REPORT_BY_DATE',
    GETTING_REPORT_BY_DATE: 'GETTING_REPORT_BY_DATE',
    GET_REPORT_BY_DATE_SUCCESS: 'GET_REPORT_BY_DATE_SUCCESS',
    GET_REPORT_BY_DATE_FAILSE: 'GET_REPORT_BY_DATE_FAILSE',

    GET_REPORT_BY_ORDER: 'GET_REPORT_BY_ORDER',
    GETTING_REPORT_BY_ORDER: 'GETTING_REPORT_BY_ORDER',
    GET_REPORT_BY_ORDER_SUCCESS: 'GET_REPORT_BY_ORDER_SUCCESS',
    GET_REPORT_BY_ORDER_FAILSE: 'GET_REPORT_BY_ORDER_FAILSE',

    GET_REPORT_BY_FILM: 'GET_REPORT_BY_FILM',
    GETTING_REPORT_BY_FILM: 'GETTING_REPORT_BY_FILM',
    GET_REPORT_BY_FILM_SUCCESS: 'GET_REPORT_BY_FILM_SUCCESS',
    GET_REPORT_BY_FILM_FAILSE: 'GET_REPORT_BY_FILM_FAILSE',
};

export default ReportAction;