const OrderAction = {
    GET_LIST_ORDER_BY_USERID: 'GET_LIST_ORDER_BY_USERID',
    GETTING_LIST_ORDER_BY_USERID: 'GETTING_LIST_ORDER_BY_USERID',
    GET_LIST_ORDER_BY_USERID_SUCCESS: 'GET_LIST_ORDER_BY_USERID_SUCCESS',
    GET_LIST_ORDER_BY_USERID_FAILURE: 'GET_LIST_ORDER_BY_USERID_FAILURE',

    GET_LIST_ORDER_BY_STATUS: 'GET_LIST_ORDER_BY_STATUS',


    GET_ORDER_BY_ID: 'GET_ORDER_BY_ID',
    GETTING_ORDER_BY_ID: 'GETTING_ORDER_BY_ID',
    GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
    GET_ORDER_BY_ID_FAILURE: 'GET_ORDER_BY_ID_FAILURE',

    ADD_ORDER: 'ADD_ORDER',
    ADDING_ORDER: 'ADDTING_ORDER',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',

    GET_DETAIL_BY_ID: 'GET_DETAIL_BY_ID',

    CHANGE_STATUS_ORDER: 'CHANGE_STATUS_ORDER'
};

export default OrderAction;
